services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    depends_on:
      - db
  db:
    image: postgres:15
    container_name: postgres-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: sphinx-docs
    volumes:
      - ./docs:/app/docs
    ports:
      - "8080:8080"
    command: python3 -m http.server 8080 --directory /app/docs/build
    depends_on:
      - web
      - db

volumes:
  postgres_data:
